# Use nginx as the base image
FROM nginx:alpine

# Copy the entire content of the service directory into the nginx HTML directory
COPY . /usr/share/nginx/html

# Expose port 80 for the nginx server
EXPOSE 80
